/*
Ledger API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerclient

import (
	"encoding/json"
)

// TransactionCommitErrorAllOf struct for TransactionCommitErrorAllOf
type TransactionCommitErrorAllOf struct {
	ErrorCode *ErrorCode `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

// NewTransactionCommitErrorAllOf instantiates a new TransactionCommitErrorAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionCommitErrorAllOf() *TransactionCommitErrorAllOf {
	this := TransactionCommitErrorAllOf{}
	return &this
}

// NewTransactionCommitErrorAllOfWithDefaults instantiates a new TransactionCommitErrorAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionCommitErrorAllOfWithDefaults() *TransactionCommitErrorAllOf {
	this := TransactionCommitErrorAllOf{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *TransactionCommitErrorAllOf) GetErrorCode() ErrorCode {
	if o == nil || o.ErrorCode == nil {
		var ret ErrorCode
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionCommitErrorAllOf) GetErrorCodeOk() (*ErrorCode, bool) {
	if o == nil || o.ErrorCode == nil {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *TransactionCommitErrorAllOf) HasErrorCode() bool {
	if o != nil && o.ErrorCode != nil {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given ErrorCode and assigns it to the ErrorCode field.
func (o *TransactionCommitErrorAllOf) SetErrorCode(v ErrorCode) {
	o.ErrorCode = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *TransactionCommitErrorAllOf) GetErrorMessage() string {
	if o == nil || o.ErrorMessage == nil {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionCommitErrorAllOf) GetErrorMessageOk() (*string, bool) {
	if o == nil || o.ErrorMessage == nil {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *TransactionCommitErrorAllOf) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage != nil {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *TransactionCommitErrorAllOf) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o TransactionCommitErrorAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if o.ErrorMessage != nil {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionCommitErrorAllOf struct {
	value *TransactionCommitErrorAllOf
	isSet bool
}

func (v NullableTransactionCommitErrorAllOf) Get() *TransactionCommitErrorAllOf {
	return v.value
}

func (v *NullableTransactionCommitErrorAllOf) Set(val *TransactionCommitErrorAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionCommitErrorAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionCommitErrorAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionCommitErrorAllOf(val *TransactionCommitErrorAllOf) *NullableTransactionCommitErrorAllOf {
	return &NullableTransactionCommitErrorAllOf{value: val, isSet: true}
}

func (v NullableTransactionCommitErrorAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionCommitErrorAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


