/*
Ledger API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerclient

import (
	"encoding/json"
)

// ConfigInfoResponseAllOf struct for ConfigInfoResponseAllOf
type ConfigInfoResponseAllOf struct {
	Data ConfigInfo `json:"data"`
}

// NewConfigInfoResponseAllOf instantiates a new ConfigInfoResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigInfoResponseAllOf(data ConfigInfo) *ConfigInfoResponseAllOf {
	this := ConfigInfoResponseAllOf{}
	this.Data = data
	return &this
}

// NewConfigInfoResponseAllOfWithDefaults instantiates a new ConfigInfoResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigInfoResponseAllOfWithDefaults() *ConfigInfoResponseAllOf {
	this := ConfigInfoResponseAllOf{}
	return &this
}

// GetData returns the Data field value
func (o *ConfigInfoResponseAllOf) GetData() ConfigInfo {
	if o == nil {
		var ret ConfigInfo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConfigInfoResponseAllOf) GetDataOk() (*ConfigInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConfigInfoResponseAllOf) SetData(v ConfigInfo) {
	o.Data = v
}

func (o ConfigInfoResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableConfigInfoResponseAllOf struct {
	value *ConfigInfoResponseAllOf
	isSet bool
}

func (v NullableConfigInfoResponseAllOf) Get() *ConfigInfoResponseAllOf {
	return v.value
}

func (v *NullableConfigInfoResponseAllOf) Set(val *ConfigInfoResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigInfoResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigInfoResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigInfoResponseAllOf(val *ConfigInfoResponseAllOf) *NullableConfigInfoResponseAllOf {
	return &NullableConfigInfoResponseAllOf{value: val, isSet: true}
}

func (v NullableConfigInfoResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigInfoResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


