/*
Ledger API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.9.0-beta.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerclient

import (
	"encoding/json"
)

// ListLogs200Response struct for ListLogs200Response
type ListLogs200Response struct {
	Cursor ListLogs200ResponseCursor `json:"cursor"`
}

// NewListLogs200Response instantiates a new ListLogs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLogs200Response(cursor ListLogs200ResponseCursor) *ListLogs200Response {
	this := ListLogs200Response{}
	this.Cursor = cursor
	return &this
}

// NewListLogs200ResponseWithDefaults instantiates a new ListLogs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLogs200ResponseWithDefaults() *ListLogs200Response {
	this := ListLogs200Response{}
	return &this
}

// GetCursor returns the Cursor field value
func (o *ListLogs200Response) GetCursor() ListLogs200ResponseCursor {
	if o == nil {
		var ret ListLogs200ResponseCursor
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *ListLogs200Response) GetCursorOk() (*ListLogs200ResponseCursor, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *ListLogs200Response) SetCursor(v ListLogs200ResponseCursor) {
	o.Cursor = v
}

func (o ListLogs200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cursor"] = o.Cursor
	}
	return json.Marshal(toSerialize)
}

type NullableListLogs200Response struct {
	value *ListLogs200Response
	isSet bool
}

func (v NullableListLogs200Response) Get() *ListLogs200Response {
	return v.value
}

func (v *NullableListLogs200Response) Set(val *ListLogs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLogs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLogs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLogs200Response(val *ListLogs200Response) *NullableListLogs200Response {
	return &NullableListLogs200Response{value: val, isSet: true}
}

func (v NullableListLogs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLogs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


