/*
Ledger API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerclient

import (
	"encoding/json"
)

// AccountResponseAllOf struct for AccountResponseAllOf
type AccountResponseAllOf struct {
	Data Account `json:"data"`
}

// NewAccountResponseAllOf instantiates a new AccountResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountResponseAllOf(data Account) *AccountResponseAllOf {
	this := AccountResponseAllOf{}
	this.Data = data
	return &this
}

// NewAccountResponseAllOfWithDefaults instantiates a new AccountResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountResponseAllOfWithDefaults() *AccountResponseAllOf {
	this := AccountResponseAllOf{}
	return &this
}

// GetData returns the Data field value
func (o *AccountResponseAllOf) GetData() Account {
	if o == nil {
		var ret Account
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AccountResponseAllOf) GetDataOk() (*Account, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AccountResponseAllOf) SetData(v Account) {
	o.Data = v
}

func (o AccountResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAccountResponseAllOf struct {
	value *AccountResponseAllOf
	isSet bool
}

func (v NullableAccountResponseAllOf) Get() *AccountResponseAllOf {
	return v.value
}

func (v *NullableAccountResponseAllOf) Set(val *AccountResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountResponseAllOf(val *AccountResponseAllOf) *NullableAccountResponseAllOf {
	return &NullableAccountResponseAllOf{value: val, isSet: true}
}

func (v NullableAccountResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


