/*
Ledger API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerclient

import (
	"encoding/json"
)

// CreateTransactions200Response struct for CreateTransactions200Response
type CreateTransactions200Response struct {
	Cursor *Cursor `json:"cursor,omitempty"`
	Data []Transaction `json:"data"`
}

// NewCreateTransactions200Response instantiates a new CreateTransactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransactions200Response(data []Transaction) *CreateTransactions200Response {
	this := CreateTransactions200Response{}
	this.Data = data
	return &this
}

// NewCreateTransactions200ResponseWithDefaults instantiates a new CreateTransactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransactions200ResponseWithDefaults() *CreateTransactions200Response {
	this := CreateTransactions200Response{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *CreateTransactions200Response) GetCursor() Cursor {
	if o == nil || o.Cursor == nil {
		var ret Cursor
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTransactions200Response) GetCursorOk() (*Cursor, bool) {
	if o == nil || o.Cursor == nil {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *CreateTransactions200Response) HasCursor() bool {
	if o != nil && o.Cursor != nil {
		return true
	}

	return false
}

// SetCursor gets a reference to the given Cursor and assigns it to the Cursor field.
func (o *CreateTransactions200Response) SetCursor(v Cursor) {
	o.Cursor = &v
}

// GetData returns the Data field value
func (o *CreateTransactions200Response) GetData() []Transaction {
	if o == nil {
		var ret []Transaction
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateTransactions200Response) GetDataOk() (*[]Transaction, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateTransactions200Response) SetData(v []Transaction) {
	o.Data = v
}

func (o CreateTransactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Cursor != nil {
		toSerialize["cursor"] = o.Cursor
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableCreateTransactions200Response struct {
	value *CreateTransactions200Response
	isSet bool
}

func (v NullableCreateTransactions200Response) Get() *CreateTransactions200Response {
	return v.value
}

func (v *NullableCreateTransactions200Response) Set(val *CreateTransactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTransactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTransactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTransactions200Response(val *CreateTransactions200Response) *NullableCreateTransactions200Response {
	return &NullableCreateTransactions200Response{value: val, isSet: true}
}

func (v NullableCreateTransactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTransactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


