/*
Ledger API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgerclient

import (
	"encoding/json"
)

// TransactionCursorResponse struct for TransactionCursorResponse
type TransactionCursorResponse struct {
	Cursor TransactionCursor `json:"cursor"`
}

// NewTransactionCursorResponse instantiates a new TransactionCursorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionCursorResponse(cursor TransactionCursor) *TransactionCursorResponse {
	this := TransactionCursorResponse{}
	this.Cursor = cursor
	return &this
}

// NewTransactionCursorResponseWithDefaults instantiates a new TransactionCursorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionCursorResponseWithDefaults() *TransactionCursorResponse {
	this := TransactionCursorResponse{}
	return &this
}

// GetCursor returns the Cursor field value
func (o *TransactionCursorResponse) GetCursor() TransactionCursor {
	if o == nil {
		var ret TransactionCursor
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *TransactionCursorResponse) GetCursorOk() (*TransactionCursor, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *TransactionCursorResponse) SetCursor(v TransactionCursor) {
	o.Cursor = v
}

func (o TransactionCursorResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cursor"] = o.Cursor
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionCursorResponse struct {
	value *TransactionCursorResponse
	isSet bool
}

func (v NullableTransactionCursorResponse) Get() *TransactionCursorResponse {
	return v.value
}

func (v *NullableTransactionCursorResponse) Set(val *TransactionCursorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionCursorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionCursorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionCursorResponse(val *TransactionCursorResponse) *NullableTransactionCursorResponse {
	return &NullableTransactionCursorResponse{value: val, isSet: true}
}

func (v NullableTransactionCursorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionCursorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


